M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-02-27T22:41:25+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-27T22:41:25+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X58.97Y22.44
X58.97Y16.66
T2
X14.675Y42.15
X18.275Y42.15
M30
