/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f1xx.h"

#include "main.h"
#include "gpio.h"
#include "spi.h"
#include "st7735.h"
#include "display.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay_ms(uint32_t ms)
{
    volatile uint32_t count;

    while(ms--)
    {
        count = 800;

        while(count--)
        {
            __NOP();
        }
    }
}

void error_handler(void)
{
    while(1)
    {
        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(100);

        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(100);
        
        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(2000);
    }
}

QueueHandle_t xDisplayQueue;

EventGroupHandle_t xSystemFlags;

// Task function prototype
void vHomeTask(void *pvParameters);
void vDisplayTask(void *pvParameters);

int main(void)
{
    gpio_init();
    spi1_init();
    ST7735_Init();
    ST7735_FillRectangle(0, 0, ST7735_WIDTH, ST7735_HEIGHT, ST7735_BLACK);

    if(xTaskCreate(vHomeTask, "HomeTask", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    if(xTaskCreate(vDisplayTask, "DisplayTask", configMINIMAL_STACK_SIZE * 2, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    xDisplayQueue = xQueueCreate(10, sizeof(displayData_t));
    if(xDisplayQueue == NULL)
    {
        error_handler();
    }

    xSystemFlags = xEventGroupCreate();
    if(xSystemFlags == NULL)
    {
        error_handler();
    }

    vTaskStartScheduler();
    
    while(1){
        // spi1_transmit(tx_data, sizeof(tx_data));
        LED2_GPIO->BSRR |= (1 << LED2_PIN);
        LED3_GPIO->BSRR |= (1 << LED3_PIN);
        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED2_GPIO->BRR |= (1 << LED2_PIN);
        LED3_GPIO->BRR |= (1 << LED3_PIN);
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(100);
    }
}

void vHomeTask(void *pvParameters)
{
    displayData_t display_data = {
        .data_type = TEXT,
        .x_pos = 10,
        .y_pos = 10,
        .font_size = &Font_11x18,
        .colour = ST7735_WHITE,
        .bg_colour = ST7735_BLACK
    };

    uint8_t count = 0;
    for(;;)
    {
        LED2_GPIO->BSRR |= (1 << LED2_PIN);
        LED3_GPIO->BSRR |= (1 << LED3_PIN);
        vTaskDelay(pdMS_TO_TICKS(100));
        LED2_GPIO->BRR |= (1 << LED2_PIN);
        LED3_GPIO->BRR |= (1 << LED3_PIN);

        display_data.data_type = RECT;
        display_data.x_pos = 0;
        display_data.y_pos = 0;
        display_data.colour = ST7735_BLACK;
        xQueueSend(xDisplayQueue, &display_data, 0);

        display_data.data_type = TEXT;
        display_data.x_pos = 30;
        display_data.y_pos = 10;
        display_data.font_size = &Font_11x18;
        display_data.colour = ST7735_BLUE;
        display_data.bg_colour = ST7735_BLACK;
        snprintf(display_data.buf, sizeof(display_data.buf), "AZRAEL");
        xQueueSend(xDisplayQueue, &display_data, 0);

        display_data.colour = ST7735_RED;
        display_data.bg_colour = ST7735_BLACK;
        display_data.x_pos = 4;
        display_data.y_pos = 130;
        display_data.font_size = &Font_7x10;
        snprintf(display_data.buf, sizeof(display_data.buf), "Press OK to start");
        xQueueSend(xDisplayQueue, &display_data, 0);

        EventBits_t flags = xEventGroupWaitBits(xSystemFlags, PRESSED_OK_FLAG | PRESSED_EXIT_FLAG, pdTRUE, pdFALSE, portMAX_DELAY);

        if (flags & PRESSED_OK_FLAG)
        {
            // OK button was pressed
            // Handle OK button action here
            display_data.colour = ST7735_GREEN;
            display_data.bg_colour = ST7735_BLACK;
            display_data.x_pos = 4;
            display_data.y_pos = 100;
            display_data.font_size = &Font_7x10;
            snprintf(display_data.buf, sizeof(display_data.buf), "OK Pressed!");
            xQueueSend(xDisplayQueue, &display_data, 0);
        }
        else if (flags & PRESSED_EXIT_FLAG)
        {
            // EXIT button was pressed
            // Handle EXIT button action here
            display_data.colour = ST7735_RED;
            display_data.bg_colour = ST7735_BLACK;
            display_data.x_pos = 4;
            display_data.y_pos = 100;
            display_data.font_size = &Font_7x10;
            snprintf(display_data.buf, sizeof(display_data.buf), "EXIT Pressed!");
            xQueueSend(xDisplayQueue, &display_data, 0);
        }

    }
}

void vDisplayTask(void *pvParameters)
{
    displayData_t display_data = {
        .data_type = TEXT,
        .x_pos = 10,
        .y_pos = 10,
        .font_size = &Font_11x18,
        .colour = ST7735_WHITE,
        .bg_colour = ST7735_BLACK
    };

    for(;;)
    {
        if(xQueueReceive(xDisplayQueue, &display_data, portMAX_DELAY) == pdPASS)
        {
            switch(display_data.data_type)
            {
                case TEXT:
                    display_print_str_bg(display_data.x_pos, display_data.y_pos, display_data.buf, *display_data.font_size, display_data.colour, display_data.bg_colour);
                    break;
                case IMAGE:
                    // display_print_image(display_data.x_pos, display_data.y_pos, display_data.buf, display_data.width, display_data.height);
                    break;
                case RECT:
                    // display_draw_rectangle(display_data.x_pos, display_data.y_pos, display_data.width, display_data.height, display_data.colour);
                    break;
                default:
                    // Handle unknown data type
                    break;
                // Handle other data types (e.g., images) here
            }
        }
    }
}

void vApplicationStackOverflowHook( TaskHandle_t xTask, char *pcTaskName )
{
    ( void ) xTask;
    ( void ) pcTaskName;

    configASSERT( ( pcTaskName == NULL ) );
    for( ;; )
    {
        error_handler();
    }
}

/** Button Interrupt Handler */
void EXTI15_10_IRQHandler(void)
{
    // Check if EXTI11 (OK button) triggered the interrupt
    if (EXTI->PR & (1 << OK_BTN_PIN))
    {
        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        xEventGroupSetBits(xSystemFlags, PRESSED_OK_FLAG);
        EXTI->PR |= (1 << OK_BTN_PIN); // Clear the pending bit by writing 1
        // Handle OK button press here
    }

    // Check if EXTI10 (EXIT button) triggered the interrupt
    if (EXTI->PR & (1 << EXIT_BTN_PIN))
    {
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        xEventGroupSetBits(xSystemFlags, PRESSED_EXIT_FLAG);
        EXTI->PR |= (1 << EXIT_BTN_PIN); // Clear the pending bit by writing 1
        // Handle EXIT button press here
    }
}