/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "FreeRTOSConfig.h"
#include "projdefs.h"
#include "stm32f1xx.h"

#include "main.h"
#include "gpio.h"
#include "spi.h"
#include "i2c.h"
#include "lis3dh.h"
#include "st7735.h"
#include "display.h"
#include "assets.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define OBSTACLES_NO 2
#define OBSTACLE_SPEED 5
#define FIGHTER_Y 140

void delay_ms(uint32_t ms)
{
    volatile uint32_t count;

    while(ms--)
    {
        count = 800;

        while(count--)
        {
            __NOP();
        }
    }
}

void error_handler(void)
{
    while(1)
    {
        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(100);

        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(100);
        
        LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(2000);
    }
}

QueueHandle_t xDisplayQueue;

EventGroupHandle_t xSystemFlags;

SemaphoreHandle_t g_accel_data_mutex;
SemaphoreHandle_t i2cFreeSemaphoreHandle;
SemaphoreHandle_t g_fighter_x_mutex;

LIS3DH_Data g_accel_data;
uint8_t g_fighter_x = 0;

// Task function prototype
void vHomeTask(void *pvParameters);
void vDisplayTask(void *pvParameters);
void vMenuTask(void *pvParameters);
void vAccelerometerTask(void *pvParameters);
void vAirRaceTask(void *pvParameters);
void vSteerFighterTask(void *pvParameters);
void vUpdateObstaclesTask(void *pvParameters);

int main(void)
{
    gpio_init();
    spi1_init();
    I2C_Init();
    lis3dh_init();
    ST7735_Init();
    ST7735_FillRectangle(0, 0, ST7735_WIDTH, ST7735_HEIGHT, ST7735_BLACK);

    if(xTaskCreate(vHomeTask, "HomeTask", configMINIMAL_STACK_SIZE * 2, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    if(xTaskCreate(vDisplayTask, "DisplayTask", configMINIMAL_STACK_SIZE * 2, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    if(xTaskCreate(vMenuTask, "MenuTask", configMINIMAL_STACK_SIZE * 2, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    if(xTaskCreate(vAccelerometerTask, "AccelerometerTask", configMINIMAL_STACK_SIZE, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    if(xTaskCreate(vAirRaceTask, "AirRaceTask", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    if(xTaskCreate(vSteerFighterTask, "SteerFighterTask", configMINIMAL_STACK_SIZE, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    if(xTaskCreate(vUpdateObstaclesTask, "UpdateObstaclesTask", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL) != pdPASS)
    {
        error_handler();
    }

    xDisplayQueue = xQueueCreate(10, sizeof(displayData_t));
    if(xDisplayQueue == NULL)
    {
        error_handler();
    }

    xSystemFlags = xEventGroupCreate();
    if(xSystemFlags == NULL)
    {
        error_handler();
    }

    // create binary semaphore for g_accel_data
    g_accel_data_mutex = xSemaphoreCreateMutex();
    if(g_accel_data_mutex == NULL)
    {
        error_handler();
    }

    // create binary semaphore for i2c
    i2cFreeSemaphoreHandle = xSemaphoreCreateMutex();
    if(i2cFreeSemaphoreHandle == NULL)
    {
        error_handler();
    }

    // create binary semaphore for g_fighter_x
    g_fighter_x_mutex = xSemaphoreCreateMutex();
    if(g_fighter_x_mutex == NULL)
    {
        error_handler();
    }

    xEventGroupSetBits(xSystemFlags, HOME_FLAG); // Set the home flag to indicate we should show the home screen

    vTaskStartScheduler();
    
    while(1){
        LIS3DH_Data data;
        xSemaphoreTake(g_accel_data_mutex, portMAX_DELAY);
        lis3dh_readXYZ(&data);
        xSemaphoreGive(g_accel_data_mutex);
        // spi1_transmit(tx_data, sizeof(tx_data));
        LED2_GPIO->BSRR |= (1 << LED2_PIN);
        LED3_GPIO->BSRR |= (1 << LED3_PIN);
        // LED1_GPIO->BSRR |= (1 << LED1_PIN);
        delay_ms(100);
        LED2_GPIO->BRR |= (1 << LED2_PIN);
        LED3_GPIO->BRR |= (1 << LED3_PIN);
        // LED1_GPIO->BRR |= (1 << LED1_PIN);
        delay_ms(100);
    }
}

void vHomeTask(void *pvParameters)
{
    displayData_t display_data = {
        .data_type = TEXT,
        .x_pos = 10,
        .y_pos = 10,
        .font_size = &Font_11x18,
        .colour = ST7735_WHITE,
        .bg_colour = ST7735_BLACK
    };

    for(;;)
    {
        xEventGroupWaitBits(xSystemFlags, HOME_FLAG, pdFALSE, pdTRUE, portMAX_DELAY);
        LED2_GPIO->BSRR |= (1 << LED2_PIN);
        LED3_GPIO->BSRR |= (1 << LED3_PIN);
        vTaskDelay(pdMS_TO_TICKS(100));
        LED2_GPIO->BRR |= (1 << LED2_PIN);
        LED3_GPIO->BRR |= (1 << LED3_PIN);

        display_data.data_type = RECT;
        display_data.x_pos = 0;
        display_data.y_pos = 0;
        display_data.colour = ST7735_BLACK;
        display_data.w = ST7735_WIDTH;
        display_data.h = ST7735_HEIGHT;
        xQueueSend(xDisplayQueue, &display_data, 0);

        display_data.data_type = TEXT;
        display_data.x_pos = 30;
        display_data.y_pos = 10;
        display_data.font_size = &Font_11x18;
        display_data.colour = ST7735_BLUE;
        display_data.bg_colour = ST7735_BLACK;
        snprintf(display_data.buf, sizeof(display_data.buf), "AZRAEL");
        xQueueSend(xDisplayQueue, &display_data, 0);

        display_data.colour = ST7735_RED;
        display_data.bg_colour = ST7735_BLACK;
        display_data.x_pos = 4;
        display_data.y_pos = 130;
        display_data.font_size = &Font_7x10;
        snprintf(display_data.buf, sizeof(display_data.buf), "Press OK to start");
        xQueueSend(xDisplayQueue, &display_data, 0);

        EventBits_t flags = xEventGroupWaitBits(xSystemFlags, PRESSED_OK_FLAG, pdTRUE, pdFALSE, portMAX_DELAY);

        if (flags & PRESSED_OK_FLAG)
        {
            // OK button was pressed
            xEventGroupClearBits(xSystemFlags, HOME_FLAG); // Clear the home flag to indicate we should stop showing the home screen
            xEventGroupSetBits(xSystemFlags, MENU_FLAG); // Set the menu flag to indicate we should show the menu
        }

    }
}

void vDisplayTask(void *pvParameters)
{
    displayData_t display_data = {
        .data_type = TEXT,
        .x_pos = 10,
        .y_pos = 10,
        .font_size = &Font_11x18,
        .colour = ST7735_WHITE,
        .bg_colour = ST7735_BLACK
    };

    for(;;)
    {
        if(xQueueReceive(xDisplayQueue, &display_data, portMAX_DELAY) == pdPASS)
        {
            switch(display_data.data_type)
            {
                case TEXT:
                    display_print_str_bg(display_data.x_pos, display_data.y_pos, display_data.buf, *display_data.font_size, display_data.colour, display_data.bg_colour);
                    break;
                case IMAGE:
                    display_DrawImageTransparent(display_data.x_pos, display_data.y_pos, display_data.w, display_data.h, (const uint16_t*)display_data.data, display_data.transparent_color);
                    break;
                case RECT:
                    display_FillRectangle(display_data.x_pos, display_data.y_pos, display_data.w, display_data.h, display_data.colour);
                    break;
                default:
                    // Handle unknown data type
                    break;
                // Handle other data types (e.g., images) here
            }
        }
    }
}

void vMenuTask(void *pvParameters)
{
    // clear rect
    displayData_t clear_rect = {
        .data_type = RECT,
        .x_pos = 0,
        .y_pos = 0,
        .colour = ST7735_BLACK,
        .w = ST7735_WIDTH,
        .h = ST7735_HEIGHT
    };

    // data for menu items
    displayData_t menu_item_data = {
        .data_type = TEXT,
        .x_pos = 10,
        .y_pos = 10,
        .font_size = &Font_11x18,
        .colour = ST7735_GREEN,
        .bg_colour = ST7735_BLACK
    };

    uint8_t clear_screen = 1;
    uint8_t menu_index = 0;

    for(;;)
    {
        xEventGroupWaitBits(xSystemFlags, MENU_FLAG, pdFALSE, pdTRUE, portMAX_DELAY);
        
        // Show the menu
        if (clear_screen)
        {
            xQueueSend(xDisplayQueue, &clear_rect, 0); // Clear the screen
            clear_screen = 0;
        }
        menu_item_data.x_pos = 10;
        menu_item_data.y_pos = 50;

        xSemaphoreTake(g_accel_data_mutex, portMAX_DELAY);
        int16_t accel_x = g_accel_data.y; // The device is oriented such that tilting left/right affects the y-axis
        xSemaphoreGive(g_accel_data_mutex);
        
        if (accel_x > LIS3DH_TILT_THRESHOLD){
            menu_index = 0;
            snprintf(menu_item_data.buf, sizeof(menu_item_data.buf), "Menu Item 1");
            xQueueSend(xDisplayQueue, &menu_item_data, portMAX_DELAY);
        } else if (accel_x < -LIS3DH_TILT_THRESHOLD){
            menu_index = 1;
            snprintf(menu_item_data.buf, sizeof(menu_item_data.buf), "Menu Item 2");
            xQueueSend(xDisplayQueue, &menu_item_data, portMAX_DELAY);
        } else {
            menu_index = 2;
            snprintf(menu_item_data.buf, sizeof(menu_item_data.buf), "SPACE RACER");
            xQueueSend(xDisplayQueue, &menu_item_data, portMAX_DELAY);
        }


        EventBits_t flags = xEventGroupWaitBits(xSystemFlags, PRESSED_EXIT_FLAG | PRESSED_OK_FLAG, pdTRUE, pdFALSE, 0);
        
        if (flags & PRESSED_EXIT_FLAG)
        {
            // EXIT button was pressed
            clear_screen = 1;
            xEventGroupClearBits(xSystemFlags, MENU_FLAG); // Clear the menu flag to indicate we should stop showing the menu
            xEventGroupSetBits(xSystemFlags, HOME_FLAG); // Set the home flag to indicate we should show the home screen
        }
         else if (flags & PRESSED_OK_FLAG)
        {
            clear_screen = 1;
            xEventGroupClearBits(xSystemFlags, MENU_FLAG); // Clear the menu flag to indicate we should stop showing the menu
            switch(menu_index)
            {
                case 2:
                    xEventGroupSetBits(xSystemFlags, START_AIRRACE_FLAG); // Set the flag to indicate we should start the
                    break;
                default:
                    break;
            }
            // OK button was pressed while in the menu - handle accordingly (e.g., select menu item)
        }

    }
}

void vAccelerometerTask(void *pvParameters)
{
    for(;;)
    {
        LIS3DH_Data data;
        lis3dh_readXYZ(&data);
        xSemaphoreTake(g_accel_data_mutex, portMAX_DELAY);
        g_accel_data = data; // Update global accelerometer data
        xSemaphoreGive(g_accel_data_mutex);
        vTaskDelay(pdMS_TO_TICKS(10)); // Adjust delay as needed
    }
}

void vAirRaceTask(void *pvParameters)
{
    for(;;)
    {
        xEventGroupWaitBits(xSystemFlags, START_AIRRACE_FLAG, pdFALSE, pdTRUE, portMAX_DELAY);

        EventBits_t flags = xEventGroupWaitBits(xSystemFlags, PRESSED_EXIT_FLAG, pdTRUE, pdFALSE, 0);
        
        if (flags & PRESSED_EXIT_FLAG)
        {
            // EXIT button was pressed
            xEventGroupClearBits(xSystemFlags, START_AIRRACE_FLAG); 
            xEventGroupSetBits(xSystemFlags, MENU_FLAG);
        }
        vTaskDelay(pdMS_TO_TICKS(10)); // Adjust delay as needed for game loop timing
    }
}

void vSteerFighterTask(void *pvParameters)
{
    displayData_t display_data = {
        .data_type = IMAGE,
        .x_pos = 0,
        .y_pos = 140,
        .w = FIGHTER_WIDTH,
        .h = FIGHTER_HEIGHT,
        .bg_colour = ST7735_BLACK,
        .data = (const uint16_t *)fighter_image,
        .transparent_color = ST7735_BLACK
    };

    for(;;)
    {
        xEventGroupWaitBits(xSystemFlags, START_AIRRACE_FLAG, pdFALSE, pdTRUE, portMAX_DELAY); 
        // Update fighter position based on accelerometer data
        xSemaphoreTake(g_accel_data_mutex, portMAX_DELAY);
        int16_t accel_x = g_accel_data.y; // The device is oriented such that tilting left/right affects the y-axis
        xSemaphoreGive(g_accel_data_mutex);

        uint8_t new_x = (DISPLAY_WIDTH * (accel_x + LIS3DH_TILT_THRESHOLD)) / (2 * LIS3DH_TILT_THRESHOLD);
	    new_x = (new_x / (DISPLAY_WIDTH / 4)) * (DISPLAY_WIDTH / 4); // Snap to 4 columns

        if (new_x != display_data.x_pos) {
            display_data.w = DISPLAY_WIDTH;
            display_data.data_type = RECT;
            display_data.colour = ST7735_BLACK;
            xQueueSend(xDisplayQueue, &display_data, 0); // Clear the fighter area
            display_data.x_pos = new_x;
            display_data.data_type = IMAGE;
            display_data.w = FIGHTER_WIDTH;
            xQueueSend(xDisplayQueue, &display_data, 0);
        }

        vTaskDelay(pdMS_TO_TICKS(10)); // Adjust delay as needed for smoother movement
    }
}

void vUpdateObstaclesTask(void *pvParameters)
{
    displayData_t clear_rect = {
        .data_type = RECT,
        .x_pos = 0,
        .y_pos = 0,
        .colour = ST7735_BLACK,
        .w = OBSTACLE_WIDTH,
    };

    displayData_t obs_arr[OBSTACLES_NO];
    for (uint8_t i = 0; i < OBSTACLES_NO; i++) {
        obs_arr[i].data_type = IMAGE;
        obs_arr[i].x_pos = 0;
        obs_arr[i].y_pos = 0;
        obs_arr[i].w = OBSTACLE_WIDTH;
        obs_arr[i].h = OBSTACLE_HEIGHT;
        obs_arr[i].bg_colour = ST7735_BLACK;
        obs_arr[i].data = (const uint16_t *)obstacle_image;
        obs_arr[i].transparent_color = ST7735_BLACK;
    }

    srand(49250);
	for(uint8_t i = 0; i < OBSTACLES_NO; i++){
		obs_arr[i].x_pos = (((rand() % DISPLAY_WIDTH) / 32) * 32);
		obs_arr[i].y_pos = -(((rand() % 200) / (FIGHTER_HEIGHT + 10)) * (FIGHTER_HEIGHT + 10));
		obs_arr[i].data = (const uint16_t *) obstacle_image;
	}

    for(;;)
    {
        xEventGroupWaitBits(xSystemFlags, START_AIRRACE_FLAG, pdFALSE, pdTRUE, portMAX_DELAY); 
        xSemaphoreTake(g_fighter_x_mutex, portMAX_DELAY);
        uint8_t fighter_x = g_fighter_x; // Get current fighter x
        xSemaphoreGive(g_fighter_x_mutex);
        // Update obstacle positions and check for collisions here
    	for(uint8_t i = 0; i < OBSTACLES_NO; i++){
            // check for collision with fighter here
            if(obs_arr[i].y_pos > FIGHTER_Y){
                if((obs_arr[i].x_pos >= fighter_x && obs_arr[i].x_pos < (fighter_x + FIGHTER_WIDTH)) || 
                   ((obs_arr[i].x_pos + OBSTACLE_WIDTH) > fighter_x && (obs_arr[i].x_pos + OBSTACLE_WIDTH) <= (fighter_x + FIGHTER_WIDTH))){
                    // Collision detected - handle game over
                    for(uint8_t i = 0; i < OBSTACLES_NO; i++){
                        obs_arr[i].x_pos = (((rand() % DISPLAY_WIDTH) / 32) * 32);
                        obs_arr[i].y_pos = -(((rand() % 200) / (FIGHTER_HEIGHT + 10)) * (FIGHTER_HEIGHT + 10));
                        obs_arr[i].data = (const uint16_t *) obstacle_image;
                    }
                    
                    xEventGroupClearBits(xSystemFlags, START_AIRRACE_FLAG); 
                    xEventGroupSetBits(xSystemFlags, MENU_FLAG);
                    break;
                }
            }

            if(obs_arr[i].y_pos > (DISPLAY_HEIGHT + OBSTACLE_HEIGHT)){
                obs_arr[i].x_pos = (((rand() % DISPLAY_WIDTH) / 32) * 32);
                obs_arr[i].y_pos = -OBSTACLE_HEIGHT;
            } else {
                obs_arr[i].y_pos += OBSTACLE_SPEED;
            }
            int16_t clear_rect_y = obs_arr[i].y_pos - OBSTACLE_SPEED;
            clear_rect.x_pos = obs_arr[i].x_pos;
            clear_rect.y_pos = clear_rect_y;

            clear_rect.h = (OBSTACLE_HEIGHT - OBSTACLE_SPEED - 10);
            xQueueSend(xDisplayQueue, &clear_rect, 0);
            xQueueSend(xDisplayQueue, &obs_arr[i], 0);
        }
        vTaskDelay(pdMS_TO_TICKS(10)); // Adjust delay as needed for obstacle movement timing
    }
}

void vApplicationStackOverflowHook( TaskHandle_t xTask, char *pcTaskName )
{
    ( void ) xTask;
    ( void ) pcTaskName;

    configASSERT( ( pcTaskName == NULL ) );
    for( ;; )
    {
        error_handler();
    }
}